[package]
name = "mcim-rust-api"
version = "0.1.0"
edition = "2021"
authors = ["z0z0r4@outlook.com"]
description = "MCIM API rewritten in Rust"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bson = {version = "2.0", features = ["chrono-0_4"] }
mongodb = { version = "2.4.0", features = ["tokio-runtime"] }
dotenvy = "0.15"
chrono = { version = "0.4.41", features = ["serde"] }
futures = "0.3.31"
serde-value = "0.7.0"
utoipa = { version = "5.3.1", features = ["actix_extras", "chrono"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
utoipa-actix-web = "0.1.2"
utoipauto = "=0.3.0-alpha.2"
