[package]
name = "mcim-rust-api"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "一个用Rust编写的信息管理API"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bson = {version = "2.0", features = ["chrono-0_4"] }
mongodb = { version = "2.4.0", features = ["tokio-runtime"] }
dotenvy = "0.15"
chrono = { version = "0.4.41", features = ["serde"] }
futures = "0.3.31"