# x-logging: &default-logging
#   driver: "local"
#   options:
#     max-size: "20m"
#     max-file: "3"

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    max-size: "20m"
    max-file: "3"
    keep-file: "true"

services:
  mongodb:
    # 容器的名称为 mongo
    container_name: mongo
    # 使用的镜像名称
    image: mongo:latest
    # 当 docker 服务启动后，自动启动 mongodb 容器
    restart: always
    # 对外映射的端口
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # 宿主机硬盘目录映射容器内的存放数据的目录
    volumes:
      - /data/db:/data/db
      - ./config/mongod.conf:/etc/mongod.conf

    command:
      - "--bind_ip_all"
    # logging: *default-logging
    logging: *loki-logging
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 200M

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    # logging: *default-logging
    logging: *loki-logging
    volumes: 
      - ./config/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 200M

  mcim-rust-api:
    container_name: mcim-rust-api
    image: mcim-rust-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      PORT: 8080
      MONGODB_URI: "mongodb://root:example@mongodb:27017"
      REDIS_URL: "redis://redis:6379"
      CURSEFORGE_API_URL: "https://api.curseforge.com"
      MODRINTH_API_URL: "https://api.modrinth.com"
      CURSEFORGE_API_KEY: "your_curseforge_api_key"
    # logging: *default-logging
    logging: *loki-logging
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 300M