name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        just mongodb-tool-install
        just import-data

    - name: Run tests
      run: cargo test --verbose

    - name: Build
      run: |
        cargo build --release --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: target/release/mcim-rust-api.exe