name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Cargo
      uses: Swatinem/rust-cache@v2

    - name: Install just
      uses: extractions/setup-just@v2
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0

    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0

    - name: Install MongoDB Database Tools
      run: |
        curl -O https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.12.2.deb 
        sudo dpkg -i mongodb-database-tools-ubuntu2404-x86_64-100.12.2.deb
        sudo apt-get install -f -y

    - name: Install Redis tool
      run: |
        sudo apt-get install lsb-release curl gpg
        curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
        sudo chmod 644 /usr/share/keyrings/redis-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
        sudo apt-get update
        sudo apt install redis-tools

    - name: Install dependencies
      run: |
        just import-data

    - name: Run tests
      run: cargo test --verbose

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          cargo build --release --verbose --bin mcim-rust-api

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/release/mcim-rust-api
